name: ecosed_core
description: "EcosedCore"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ecosed_shell:
    path: packages/ecosed_shell

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
